### ISSUE TITLE
Wrong checkpoint #1

### ISSUE THREAD

**Issue by AleixBueso** [CITMProject3/Project3#103]
At the harbor, at the start the respawn forces you to take the hard road. It should let you choose.
![bug 2](https://cloud.githubusercontent.com/assets/10940493/26834545/eee694dc-4ad5-11e7-9b1e-cb5d8dfb65e7.png)

**Comment by SenyoraCatolica** [comment]
jo diria que aixo es enhancement. Segueix aixi molt be!!

**Comment by RogerOlasz** [comment]
That's not a wrong checkpoint.
