### ISSUE TITLE
Car 1 goes to infinity on "start_in_game: true" and car 2 goes backwards

### ISSUE THREAD

**Issue by auusi9** [CITMProject3/Project3#56]
**Steps to reproduce:**
1. Open configuration.json and set "start_in_game": true. Make sure there is a current scene.
2. Start de game clicking on engine.exe 
3. Look at the cars go crassi.

Frequency: 100% on scene 2, not tested in other scenes.

**Comment by Vulpem** [comment]
Should work now. Needs testing, though.
