### ISSUE TITLE
Place acces that should be inaccessible

### ISSUE THREAD

**Issue by SenyoraCatolica** [CITMProject3/Project3#85]
Play the umi gohan map
in the zone of the broken bridge you can jup to the mall village in the left side
The car dones not collide with anything

There should be colliders or something to cut the path

![bug3](https://cloud.githubusercontent.com/assets/10940505/26791221/aa54cfe2-4a16-11e7-9633-eb4e1c3610df.jpg)

**Comment by RogerOlasz** [comment]
Solved. Actallu there are a invisible wall that will stops the player if he tries to reach the coast village.
