### ISSUE TITLE
Drift in the air

### ISSUE THREAD

**Issue by SenyoraCatolica** [CITMProject3/Project3#86]
Play the map omi gohan (the one with drift now)
In the only jump of the map do the drift while jumping
You can actually drift in the air and you should not be able to do that

**Comment by Vulpem** [comment]
Speak with the designers. It was requested that the drift didn't cancel while airborne, and this is what's happening here.

**Comment by Vulpem** [comment]
You could START to drift on the air, but not anymore. So this should be fixed.
