### ISSUE TITLE
Hidden turbo

### ISSUE THREAD

**Issue by SenyoraCatolica** [CITMProject3/Project3#88]
Play the Umi Gohan map
Just before the line lap there is a hidden turbo.

Here the video:
https://drive.google.com/open?id=0B_f_RtJ2CmCuYlBzWVlXMHFGWWc

**Comment by Vulpem** [comment]
![captura](https://cloud.githubusercontent.com/assets/10261951/26793316/d58ce40e-4a1d-11e7-8cc2-f1a6ec8af642.JPG)
here it is!

**Comment by RogerOlasz** [comment]
Solved. Actually you can see the turbopad :D
