### ISSUE TITLE
Cross ramp in opposite direction

### ISSUE THREAD

**Issue by SenyoraCatolica** [CITMProject3/Project3#90]
Play the Umi Gohan map

In the zone of the ramps before the lap line, you can cross the right side ramp if you go in the opposite direction

Video here:
https://drive.google.com/open?id=0B_f_RtJ2CmCuZk1tS0VwT1VMbE0

**Comment by RogerOlasz** [comment]
Solved. Now collider is bigger so you can't cross it.
