### ISSUE TITLE
No respawning in water

### ISSUE THREAD

**Issue by AleixBueso** [CITMProject3/Project3#93]
When crossing the fences with the ramp you can end up in the water and the kart doesn't respawn at the last checkpoint.

If you en up at the beach or inside a prop the kart won't respawn either.

![bug 1](https://cloud.githubusercontent.com/assets/10940493/26795406/d74b25aa-4a25-11e7-8ab4-6e5a4675575f.png)

**Comment by AleixBueso** [comment]
If you en up at the beach or inside a prop the kart won't respawn either.

**Comment by SenyoraCatolica** [comment]
Ya esta posat aquet
