### ISSUE TITLE
Car positions UI does not work

### ISSUE THREAD

**Issue by SenyoraCatolica** [CITMProject3/Project3#95]
You can pass the other car or go behind it but the position does not work properly

Video here:
https://drive.google.com/open?id=0B_f_RtJ2CmCuSzBKZFNOWHljeFE

**Comment by Vulpem** [comment]
The issue is that the kart that's not moving is inside a checkpoint, and the position is measured with the distance from it. It isn't representative of what will happen in game. And, when any checkpoint is hit, it will fix itself. Fixing this would take a long time and won't happen during a race.
